<?php
date_default_timezone_set('Asia/Manila');
include '../../../init.php';
$db = new mysqli(DB_HOST, DB_USER, DB_PASSWORD, DB_NAME);
require $_SERVER['DOCUMENT_ROOT']."/Plugins/PHPExcel/Classes/PHPExcel.php";
require $_SERVER['DOCUMENT_ROOT']."/Modules/Binalot_Management/class/Class.inventory.php";
require $_SERVER['DOCUMENT_ROOT']."/Modules/Binalot_Management/class/Class.functions.php";
$function = new BINALOTFunctions;
$inventory = new BINALOTInventory;
$objRMSExcel = new PHPExcel();
$debugging = 0;

$years = $_REQUEST['years'];
$months = $_REQUEST['months'];
$days = $_REQUEST['days'];

$app_user = $_SESSION['binalot_appnameuser'];
$date = date("F d, Y @ h:i A");
$title_date = date("Ymdhis");
$titleText = "DAILY INVENTORY REPORT";

	/* @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ REPORT HEADER @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ */
	$objRMSExcel->getActiveSheet()->SetCellValue('A1',$titleText);
	$objRMSExcel->getActiveSheet()->mergeCells('A1:I1');
	$objRMSExcel->getActiveSheet()->getStyle('A1:I1')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
	$objRMSExcel->getActiveSheet()->getStyle("A1")->getFont()->setBold(true);
	$objRMSExcel->getActiveSheet()->getStyle('A1')->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID)->getStartColor()->setRGB('bddbe5');
	$objRMSExcel->getActiveSheet()->getStyle("A1")->getFont()->setSize(18);
	$objRMSExcel->getActiveSheet()->SetCellValue('A2', "Generated By - ". $app_user ." on ".$date);
	$objRMSExcel->getActiveSheet()->mergeCells('A2:I2');
	$objRMSExcel->getActiveSheet()->getStyle('A2:I2')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
	$objRMSExcel->getActiveSheet()->getStyle("A1")->getFont()->setSize(14);

	$totalBranchCount = 0;
	$query = "SELECT cluster FROM tbl_cluster WHERE active=1";
	$results = $db->query($query);

	$startColumn = 'A3'; // Starting column for merging

	while ($ROW = mysqli_fetch_array($results))
	{
	    $cluster = $ROW['cluster'];
	    $branch_cnt = $function->CountBranch($cluster, $db);    
	
	    // Calculate the ending column based on the branch count
	    $endColumnIndex = PHPExcel_Cell::columnIndexFromString(substr($startColumn, 0, 1)) + $branch_cnt - 1;
	    $endColumn = PHPExcel_Cell::stringFromColumnIndex($endColumnIndex) . substr($startColumn, 1);
	
	    // Merge the cells
	    $objRMSExcel->getActiveSheet()->mergeCells($startColumn.':'.$endColumn);
	
	    // Update the startColumn for the next cluster
	    $startColumn = PHPExcel_Cell::stringFromColumnIndex($endColumnIndex + 1) . substr($startColumn, 1);
	}


















if($debugging == 0)
{
	/* ################################################################################################ */
	/* ##################################### EXCEL OUTPUT DATA ######################################## */
	/* ################################################################################################ */
	header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
	header('Content-Disposition: attachment;filename="'.$titleText.'__REPORT_'.$title_date.'.xlsx"');
	header('Cache-Control: max-age=0');
	$objWriter = PHPExcel_IOFactory::createWriter($objRMSExcel, 'Excel2007');
	ob_start();
	$objWriter->save('php://output');
	$fileData = ob_get_clean();
	echo $fileData;
	/* ################################################################################################ */
	/* ############################### CREATED BY RONAN SARBON 2023 ################################### */
	/* ################################################################################################ */
}
function generateExcelColumnNames($maxCount) {
    $columns = array();
    $letters = range('A', 'Z');

    $singleLetterCount = min(26, $maxCount);
    for ($i = 0; $i < $singleLetterCount; $i++) {
        $columns[] = $letters[$i];
    }
    $remainingCount = $maxCount - $singleLetterCount;
    if ($remainingCount > 0) {
        $doubleLetterCount = min(26, $remainingCount);
        for ($i = 0; $i < $doubleLetterCount; $i++) {
            foreach ($letters as $secondLetter) {
                $columns[] = $letters[$i] . $secondLetter;
                $remainingCount--;
                if ($remainingCount === 0) {
                    break 2; // Exit both loops when remainingCount reaches 0
                }
            }
        }
    }
    return $columns;
}
?>