<?php
date_default_timezone_set('Asia/Manila');
include '../../../init.php';
$db = new mysqli(DB_HOST, DB_USER, DB_PASSWORD, DB_NAME);
require $_SERVER['DOCUMENT_ROOT']."/Plugins/PHPExcel/Classes/PHPExcel.php";
$app_user = $_SESSION['dbc_appnameuser'];
$date = date("F d, Y @ h:i A");
$title_date = date("Ymdhis");
$objRMSExcel = new PHPExcel();
$sqlList = $_REQUEST['columns'];
$tableName = $_REQUEST['table'];
$titleText = str_replace("dbc_","", $tableName);
$titleText = strtoupper($titleText);
$titleText = str_replace("_", " ", $titleText);
$columnsArray = explode(',', $_REQUEST['columns']);
$colCount = count($columnsArray);
$excelColumns = generateExcelColumnNames($colCount);
$lastLetter = end($excelColumns);

foreach ($excelColumns as $columnLetter) {
	$objRMSExcel->getActiveSheet()->getColumnDimension($columnLetter)->setWidth(10);
}
$objRMSExcel->getActiveSheet()->SetCellValue('A1', $titleText." REPORT");
$objRMSExcel->getActiveSheet()->mergeCells('A1:'.$lastLetter.'1' );
$objRMSExcel->getActiveSheet()->getStyle('A1:'.$lastLetter.'1')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
$objRMSExcel->getActiveSheet()->getStyle("A1")->getFont()->setBold(true);
$objRMSExcel->getActiveSheet()->getStyle('A1')->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID)->getStartColor()->setRGB('bddbe5');
$objRMSExcel->getActiveSheet()->getStyle("A1")->getFont()->setSize(18);
$objRMSExcel->getActiveSheet()->SetCellValue('A2', "Generated By - ". $app_user ." on ".$date);
$objRMSExcel->getActiveSheet()->mergeCells('A2:'.$lastLetter.'2' );
$objRMSExcel->getActiveSheet()->getStyle('A2:'.$lastLetter.'2')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
$objRMSExcel->getActiveSheet()->getStyle("A1")->getFont()->setSize(14);

foreach ($columnsArray as $index => $column)
{
    $col = str_replace("_", " ", $column);
    $col = strtoupper($col);
    $columnLetter = $excelColumns[$index]; 
    $objRMSExcel->getActiveSheet()->SetCellValue($columnLetter."3", $col);
    $objRMSExcel->getActiveSheet()->getStyle($columnLetter."3")->getFont()->setBold(true);

//    $objRMSExcel->getActiveSheet()->getStyle($columnLetter."3")->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID)->getStartColor()->setRGB('b1b2b2');
//    $objRMSExcel->getActiveSheet()->getStyle($columnLetter."3")->getBorders()->getAllBorders()->setBorderStyle(PHPExcel_Style_Border::BORDER_THIN)->getColor()->setRGB('ffffff');
}
$sqlData="SELECT $sqlList FROM $tableName";
$dataResult = mysqli_query($db,$sqlData);
$i = 4;$numbering = 1;
while ($rows = mysqli_fetch_assoc($dataResult))
{
    foreach ($columnsArray as $index => $column)
    {
		$columnLetter = $excelColumns[$index];        
        $objRMSExcel->getActiveSheet()->SetCellValue($columnLetter . $i, $rows[$column]);
        if ($index === 0) {
		    $objRMSExcel->getActiveSheet()->getStyle($columnLetter . $i)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
		} else {
		    $objRMSExcel->getActiveSheet()->getStyle($columnLetter . $i)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
		}        
    }    
    $i++;
}
/* ################################################################################################ */
/* ##################################### EXCEL OUTPUT DATA ######################################## */
/* ################################################################################################ */
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment;filename="'.$titleText.'__REPORT_'.$title_date.'.xlsx"');
header('Cache-Control: max-age=0');
$objWriter = PHPExcel_IOFactory::createWriter($objRMSExcel, 'Excel2007');
ob_start();
$objWriter->save('php://output');
$fileData = ob_get_clean();
echo $fileData;
/* ################################################################################################ */
/* ############################### CREATED BY RONAN SARBON 2023 ################################### */
/* ################################################################################################ */
function generateExcelColumnNames($maxCount) {
    $columns = array();
    $letters = range('A', 'Z');

    $singleLetterCount = min(26, $maxCount);
    for ($i = 0; $i < $singleLetterCount; $i++) {
        $columns[] = $letters[$i];
    }
    $remainingCount = $maxCount - $singleLetterCount;
    if ($remainingCount > 0) {
        $doubleLetterCount = min(26, $remainingCount);
        for ($i = 0; $i < $doubleLetterCount; $i++) {
            foreach ($letters as $secondLetter) {
                $columns[] = $letters[$i] . $secondLetter;
                $remainingCount--;
                if ($remainingCount === 0) {
                    break 2; // Exit both loops when remainingCount reaches 0
                }
            }
        }
    }
    return $columns;
}