<?php
/*
	###################################################################
	##                    							                 ##
	##                   CODED BY RONAN SARBON 2023                  ##
	##                    							                 ##
	###################################################################
*/
date_default_timezone_set('Asia/Manila');
include '../../../init.php';
$db = new mysqli(DB_HOST, DB_USER, DB_PASSWORD, DB_NAME);	
require_once $_SERVER['DOCUMENT_ROOT']."/Plugins/PHPExcel/Classes/PHPExcel.php";
require $_SERVER['DOCUMENT_ROOT']."/Modules/DBC_Management/class/Class.functions.php";
require $_SERVER['DOCUMENT_ROOT']."/Modules/DBC_Management/class/Class.inventory.php";
$function = new DBCFunctions;
$inventory = new DBCInventory;
$objRMSExcel = new PHPExcel();
$generated_by = $_SESSION['dbc_appnameuser'];
$recipient = $_REQUEST['recipient'];
$year = $_REQUEST['year']; 
$month = $_REQUEST['month']; 
$week = $_REQUEST['week'];
$month_name= date("F", strtotime($year."-".$month));

$report_text = $recipient. " Inventory Report | For the month of: ".$month_name." | Generated By: ".$generated_by." | Date Generated: ".date("F d, Y @ h:i A");

function generateExcelColumnNames($startColumn, $endColumn) {
    $columns = array();

    $currentColumn = $startColumn;

    while ($currentColumn !== $endColumn) {
        $columns[] = $currentColumn;

        if ($currentColumn === 'Z') {
            $currentColumn = 'AA';
        } elseif ($currentColumn === 'AZ') {
            $currentColumn = 'BA';
        } else {
            $currentColumn++;
        }
    }

    $columns[] = $endColumn; 

    return $columns;
}
$styleArray = array('borders' => array('allborders' => array('style' => PHPExcel_Style_Border::BORDER_THIN)));

$objRMSExcel->getActiveSheet()->SetCellValue('A1', $report_text);
$objRMSExcel->getActiveSheet()->mergeCells('A1:AX1');
$objRMSExcel->getActiveSheet()->getStyle("A1")->getFont()->setBold(true);
$objRMSExcel->getActiveSheet()->getStyle('A1:E1')->applyFromArray($styleArray);


$objRMSExcel->getActiveSheet()->SetCellValue('A2', "INVENTORY");
$objRMSExcel->getActiveSheet()->mergeCells('A2:E2');
$objRMSExcel->getActiveSheet()->getStyle('A2:E2')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
$objRMSExcel->getActiveSheet()->getStyle("A2")->getFont()->setBold(true);
$objRMSExcel->getActiveSheet()->getStyle('A2:E2')->applyFromArray($styleArray);
$objRMSExcel->getActiveSheet()->getStyle('A2')->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID)->getStartColor()->setRGB('0d6efd');
$objRMSExcel->getActiveSheet()->getStyle('A2')->getFont()->getColor()->setRGB ('FFFFFF');

$objRMSExcel->getActiveSheet()->SetCellValue('F2', "DELIVERIES IN");
$objRMSExcel->getActiveSheet()->mergeCells('F2:K2');
$objRMSExcel->getActiveSheet()->getStyle('F2:K2')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
$objRMSExcel->getActiveSheet()->getStyle("F2")->getFont()->setBold(true);
$objRMSExcel->getActiveSheet()->getStyle('F2:K2')->applyFromArray($styleArray);
$objRMSExcel->getActiveSheet()->getStyle('F2')->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID)->getStartColor()->setRGB('ffa500');
$objRMSExcel->getActiveSheet()->getStyle('F2')->getFont()->getColor()->setRGB ('FFFFFF');

$objRMSExcel->getActiveSheet()->SetCellValue('L2', "INVENTORY OUT");
$objRMSExcel->getActiveSheet()->mergeCells('L2:AQ2');
$objRMSExcel->getActiveSheet()->getStyle('L2:AQ2')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
$objRMSExcel->getActiveSheet()->getStyle("L2")->getFont()->setBold(true);
$objRMSExcel->getActiveSheet()->getStyle('L2:AQ2')->applyFromArray($styleArray);
$objRMSExcel->getActiveSheet()->getStyle('L2')->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID)->getStartColor()->setRGB('ffc107');
$objRMSExcel->getActiveSheet()->getStyle('L2')->getFont()->getColor()->setRGB ('FFFFFF');

$objRMSExcel->getActiveSheet()->SetCellValue('AR2', "TOTAL SUMMARY");
$objRMSExcel->getActiveSheet()->mergeCells('AR2:AX2');
$objRMSExcel->getActiveSheet()->getStyle('AR2:AX2')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
$objRMSExcel->getActiveSheet()->getStyle("AR2")->getFont()->setBold(true);
$objRMSExcel->getActiveSheet()->getStyle('AR2:AX2')->applyFromArray($styleArray);
$objRMSExcel->getActiveSheet()->getStyle('AR2')->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID)->getStartColor()->setRGB('dc3545');
$objRMSExcel->getActiveSheet()->getStyle('AR2')->getFont()->getColor()->setRGB ('FFFFFF');


$objRMSExcel->getActiveSheet()->getColumnDimension('A')->setWidth(5);
$objRMSExcel->getActiveSheet()->getColumnDimension('B')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('C')->setWidth(35);
$objRMSExcel->getActiveSheet()->getColumnDimension('D')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('E')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('F')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('G')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('H')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('I')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('J')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('K')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('L')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('M')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('N')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('O')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('P')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('Q')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('R')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('S')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('T')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('U')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('V')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('W')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('X')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('Y')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('Z')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('AA')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('AB')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('AC')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('AD')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('AE')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('AF')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('AG')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('AH')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('AI')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('AJ')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('AK')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('AL')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('AM')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('AN')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('AO')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('AP')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('AQ')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('AR')->setWidth(15);
$objRMSExcel->getActiveSheet()->getColumnDimension('AS')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('AT')->setWidth(15);
$objRMSExcel->getActiveSheet()->getColumnDimension('AU')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('AV')->setWidth(15);
$objRMSExcel->getActiveSheet()->getColumnDimension('AW')->setWidth(12);
$objRMSExcel->getActiveSheet()->getColumnDimension('AX')->setWidth(12);
$objRMSExcel->getActiveSheet()->getStyle('A3:AX3')->applyFromArray($styleArray);

$objRMSExcel->getActiveSheet()->getStyle('A3')->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID)->getStartColor()->setRGB('aeaeae');
$objRMSExcel->getActiveSheet()->getStyle('B3:E3')->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID)->getStartColor()->setRGB('78adfb');
$objRMSExcel->getActiveSheet()->getStyle('F3:K3')->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID)->getStartColor()->setRGB('fbdb9f');
$objRMSExcel->getActiveSheet()->getStyle('L3:AQ3')->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID)->getStartColor()->setRGB('d37d36');
$objRMSExcel->getActiveSheet()->getStyle('AR3:AX3')->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID)->getStartColor()->setRGB('db858d');


$objRMSExcel->setActiveSheetIndex(0);
$objRMSExcel->getActiveSheet()->SetCellValue('A3', "#");
$objRMSExcel->getActiveSheet()->SetCellValue('B3', "ITEM CODE");
$objRMSExcel->getActiveSheet()->SetCellValue('C3', "ITEM DESCRIPTION");
$objRMSExcel->getActiveSheet()->SetCellValue('D3', "UOM");
$objRMSExcel->getActiveSheet()->SetCellValue('E3', "BEGINNING");

$objRMSExcel->getActiveSheet()->SetCellValue('F3', "WK1(1-7)");
$objRMSExcel->getActiveSheet()->SetCellValue('G3', "WK2(8-14)");
$objRMSExcel->getActiveSheet()->SetCellValue('H3', "WK3(15-21)");
$objRMSExcel->getActiveSheet()->SetCellValue('I3', "WK4(22-28)");
$objRMSExcel->getActiveSheet()->SetCellValue('J3', "WK5(29-31)");
$objRMSExcel->getActiveSheet()->SetCellValue('K3', "TOTAL");

$objRMSExcel->getActiveSheet()->SetCellValue('L3', "DAY 1");
$objRMSExcel->getActiveSheet()->SetCellValue('M3', "DAY 2");
$objRMSExcel->getActiveSheet()->SetCellValue('N3', "DAY 3");
$objRMSExcel->getActiveSheet()->SetCellValue('O3', "DAY 4");
$objRMSExcel->getActiveSheet()->SetCellValue('P3', "DAY 5");
$objRMSExcel->getActiveSheet()->SetCellValue('Q3', "DAY 6");
$objRMSExcel->getActiveSheet()->SetCellValue('R3', "DAY 7");
$objRMSExcel->getActiveSheet()->SetCellValue('S3', "DAY 8");
$objRMSExcel->getActiveSheet()->SetCellValue('T3', "DAY 9");
$objRMSExcel->getActiveSheet()->SetCellValue('U3', "DAY 10");
$objRMSExcel->getActiveSheet()->SetCellValue('V3', "DAY 11");
$objRMSExcel->getActiveSheet()->SetCellValue('W3', "DAY 12");
$objRMSExcel->getActiveSheet()->SetCellValue('X3', "DAY 13");
$objRMSExcel->getActiveSheet()->SetCellValue('Y3', "DAY 14");
$objRMSExcel->getActiveSheet()->SetCellValue('Z3', "DAY 15");
$objRMSExcel->getActiveSheet()->SetCellValue('AA3', "DAY 16");
$objRMSExcel->getActiveSheet()->SetCellValue('AB3', "DAY 17");
$objRMSExcel->getActiveSheet()->SetCellValue('AC3', "DAY 18");
$objRMSExcel->getActiveSheet()->SetCellValue('AD3', "DAY 19");
$objRMSExcel->getActiveSheet()->SetCellValue('AE3', "DAY 20");
$objRMSExcel->getActiveSheet()->SetCellValue('AF3', "DAY 21");
$objRMSExcel->getActiveSheet()->SetCellValue('AG3', "DAY 22");
$objRMSExcel->getActiveSheet()->SetCellValue('AH3', "DAY 23");
$objRMSExcel->getActiveSheet()->SetCellValue('AI3', "DAY 24");
$objRMSExcel->getActiveSheet()->SetCellValue('AJ3', "DAY 25");
$objRMSExcel->getActiveSheet()->SetCellValue('AK3', "DAY 26");
$objRMSExcel->getActiveSheet()->SetCellValue('AL3', "DAY 27");
$objRMSExcel->getActiveSheet()->SetCellValue('AM3', "DAY 28");
$objRMSExcel->getActiveSheet()->SetCellValue('AN3', "DAY 29");
$objRMSExcel->getActiveSheet()->SetCellValue('AO3', "DAY 30");
$objRMSExcel->getActiveSheet()->SetCellValue('AP3', "DAY 31");
$objRMSExcel->getActiveSheet()->SetCellValue('AQ3', "TOTAL OUT");
$objRMSExcel->getActiveSheet()->SetCellValue('AR3', "EXPTD. STKS");
$objRMSExcel->getActiveSheet()->SetCellValue('AS3', "PHY. COUNT");
$objRMSExcel->getActiveSheet()->SetCellValue('AT3', "VARIANCES");
$objRMSExcel->getActiveSheet()->SetCellValue('AU3', "UNIT PRICE");
$objRMSExcel->getActiveSheet()->SetCellValue('AV3', "VAR. AMOUNT");
$objRMSExcel->getActiveSheet()->SetCellValue('AW3', "SHORT");
$objRMSExcel->getActiveSheet()->SetCellValue('AX3', "OVER");

$cnt_start = 1;
$days_cnt = 31;
$cnt_end =  31;
if($week != 0)
{
	$columns = [];
	for ($days = $cnt_start; $days <= $cnt_end; $days++) {
	    $column = "day_" . str_pad($days, 2, '0', STR_PAD_LEFT); // Format day as two digits
	    $columns[] = $column;
	}
	$columnList = implode(', ', $columns);
	$col = "*, ".$columnList;
} else {
	$col = '*';
}

$sqlXLQuery = "SELECT * FROM dbc_itemlist WHERE recipient='$recipient'";
$xlResults = mysqli_query($db, $sqlXLQuery);
if ($xlResults->num_rows > 0)
{
    $i = 3;
    $numbering=0;
    $variance_amount_total=0;$shortages_total=0;$overages_total=0;$variances_total=0;
    $beginning=0;$weekly_1=0;$weekly_2=0;$weekly_3=0;$weekly_4=0;$weekly_5=0;$total_inv=0;
    while ($EXCELROW = mysqli_fetch_array($xlResults))
    {
	    $i++;
	    $numbering++;
	    $itemcode = $EXCELROW['item_code'];
		$weekly_1 = $inventory->getMonthlyIn(1,$itemcode,$month,$year,$db);
	    $weekly_2 = $inventory->getMonthlyIn(2,$itemcode,$month,$year,$db);
	    $weekly_3 = $inventory->getMonthlyIn(3,$itemcode,$month,$year,$db);
	    $weekly_4 = $inventory->getMonthlyIn(4,$itemcode,$month,$year,$db);
	    $weekly_5 = $inventory->getMonthlyIn(5,$itemcode,$month,$year,$db);

	    $beginning = $inventory->getInventoryBeginning($cnt_start,$cnt_end,$days_cnt,$col,$itemcode,$month,$year,$db);	   	    
	    $total_inv = ($weekly_1 + $weekly_2 + $weekly_3 + $weekly_4 + $weekly_5 + $beginning);
	    
	    $objRMSExcel->getActiveSheet()->SetCellValue('A' . $i, $numbering);
	    $objRMSExcel->getActiveSheet()->SetCellValue('B' . $i, $itemcode);
	    $objRMSExcel->getActiveSheet()->SetCellValue('C' . $i, $EXCELROW['item_description']);
	    $objRMSExcel->getActiveSheet()->SetCellValue('D' . $i, $EXCELROW['uom']);
		$objRMSExcel->getActiveSheet()->SetCellValue('E' . $i, number_format($beginning,2));
	    $objRMSExcel->getActiveSheet()->SetCellValue('F' . $i, number_format($weekly_1,2));
	    $objRMSExcel->getActiveSheet()->SetCellValue('G' . $i, number_format($weekly_2,2));
	    $objRMSExcel->getActiveSheet()->SetCellValue('H' . $i, number_format($weekly_3,2));
	    $objRMSExcel->getActiveSheet()->SetCellValue('I' . $i, number_format($weekly_4,2));
	    $objRMSExcel->getActiveSheet()->SetCellValue('J' . $i, number_format($weekly_5,2));
	    $objRMSExcel->getActiveSheet()->SetCellValue('K' . $i, number_format($total_inv,2));
	    $objRMSExcel->getActiveSheet()->getStyle('A'. $i . ':B' . $i )->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
	    $objRMSExcel->getActiveSheet()->getStyle('E'. $i . ':K' . $i )->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_RIGHT);
	    $objRMSExcel->getActiveSheet()->getStyle('A' .$i.':K'.$i)->applyFromArray($styleArray);
	    $objRMSExcel->getActiveSheet()->getStyle('B' . $i)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_TEXT);
	    $objRMSExcel->getActiveSheet()->getStyle('D'. $i)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
	    /* ---------------------------------------------------------------------------------------------- */
	
	    $total=0;
		$sqlQueryIR = "SELECT * FROM dbc_inventory_records WHERE item_code='$itemcode' AND month='$month' AND year='$year'";
		$irResults = mysqli_query($db, $sqlQueryIR);
		if (mysqli_num_rows($irResults) > 0)
		{
			while ($IRVROW = mysqli_fetch_array($irResults))
		  	{
		        for ($x = 1; $x <= 31; $x++) {
		            $td = str_pad($x, 2, '0', STR_PAD_LEFT);
		            $day = $IRVROW['day_' . $td];
            	    
            	    $objRMSExcel->getActiveSheet()->SetCellValue('L' . $i, $IRVROW['day_01']);
            	    $objRMSExcel->getActiveSheet()->SetCellValue('M' . $i, $IRVROW['day_02']);
            	    $objRMSExcel->getActiveSheet()->SetCellValue('N' . $i, $IRVROW['day_03']);
            	    $objRMSExcel->getActiveSheet()->SetCellValue('O' . $i, $IRVROW['day_04']);
            	    $objRMSExcel->getActiveSheet()->SetCellValue('P' . $i, $IRVROW['day_05']);
            	    $objRMSExcel->getActiveSheet()->SetCellValue('Q' . $i, $IRVROW['day_06']);
            	    $objRMSExcel->getActiveSheet()->SetCellValue('R' . $i, $IRVROW['day_07']);
            	    $objRMSExcel->getActiveSheet()->SetCellValue('S' . $i, $IRVROW['day_08']);
            	    $objRMSExcel->getActiveSheet()->SetCellValue('T' . $i, $IRVROW['day_09']);
            	    $objRMSExcel->getActiveSheet()->SetCellValue('U' . $i, $IRVROW['day_10']);
            	    $objRMSExcel->getActiveSheet()->SetCellValue('V' . $i, $IRVROW['day_11']);
            	    $objRMSExcel->getActiveSheet()->SetCellValue('W' . $i, $IRVROW['day_12']);
            	    $objRMSExcel->getActiveSheet()->SetCellValue('X' . $i, $IRVROW['day_13']);
            	    $objRMSExcel->getActiveSheet()->SetCellValue('Y' . $i, $IRVROW['day_14']);
            	    $objRMSExcel->getActiveSheet()->SetCellValue('Z' . $i, $IRVROW['day_15']);
            	    $objRMSExcel->getActiveSheet()->SetCellValue('AA' . $i, $IRVROW['day_16']);
            	    $objRMSExcel->getActiveSheet()->SetCellValue('AB' . $i, $IRVROW['day_17']);
            	    $objRMSExcel->getActiveSheet()->SetCellValue('AC' . $i, $IRVROW['day_18']);
            	    $objRMSExcel->getActiveSheet()->SetCellValue('AD' . $i, $IRVROW['day_19']);
            	    $objRMSExcel->getActiveSheet()->SetCellValue('AE' . $i, $IRVROW['day_20']);
            	    $objRMSExcel->getActiveSheet()->SetCellValue('AF' . $i, $IRVROW['day_21']);
            	    $objRMSExcel->getActiveSheet()->SetCellValue('AG' . $i, $IRVROW['day_22']);
            	    $objRMSExcel->getActiveSheet()->SetCellValue('AH' . $i, $IRVROW['day_23']);
            	    $objRMSExcel->getActiveSheet()->SetCellValue('AI' . $i, $IRVROW['day_24']);
            	    $objRMSExcel->getActiveSheet()->SetCellValue('AJ' . $i, $IRVROW['day_25']);
            	    $objRMSExcel->getActiveSheet()->SetCellValue('AK' . $i, $IRVROW['day_26']);
            	    $objRMSExcel->getActiveSheet()->SetCellValue('AL' . $i, $IRVROW['day_27']);
            	    $objRMSExcel->getActiveSheet()->SetCellValue('AM' . $i, $IRVROW['day_28']);
            	    $objRMSExcel->getActiveSheet()->SetCellValue('AN' . $i, $IRVROW['day_29']);
            	    $objRMSExcel->getActiveSheet()->SetCellValue('AO' . $i, $IRVROW['day_30']);
            	    $objRMSExcel->getActiveSheet()->SetCellValue('AP' . $i, $IRVROW['day_31']);
            	    $objRMSExcel->getActiveSheet()->getStyle('L' .$i.':AP'.$i)->applyFromArray($styleArray);
            	    $total += $day;
  		        }
        	}	     
		} else {
		    for ($x = 1; $x <= 31; $x++)
		    {
				$objRMSExcel->getActiveSheet()->SetCellValue('L' . $i, "0.00");
				$objRMSExcel->getActiveSheet()->SetCellValue('M' . $i, "0.00");
				$objRMSExcel->getActiveSheet()->SetCellValue('N' . $i, "0.00");
				$objRMSExcel->getActiveSheet()->SetCellValue('O' . $i, "0.00");
				$objRMSExcel->getActiveSheet()->SetCellValue('P' . $i, "0.00");
				$objRMSExcel->getActiveSheet()->SetCellValue('Q' . $i, "0.00");
				$objRMSExcel->getActiveSheet()->SetCellValue('R' . $i, "0.00");
				$objRMSExcel->getActiveSheet()->SetCellValue('S' . $i, "0.00");
				$objRMSExcel->getActiveSheet()->SetCellValue('T' . $i, "0.00");
				$objRMSExcel->getActiveSheet()->SetCellValue('U' . $i, "0.00");
				$objRMSExcel->getActiveSheet()->SetCellValue('V' . $i, "0.00");
				$objRMSExcel->getActiveSheet()->SetCellValue('W' . $i, "0.00");
				$objRMSExcel->getActiveSheet()->SetCellValue('X' . $i, "0.00");
				$objRMSExcel->getActiveSheet()->SetCellValue('Y' . $i, "0.00");
				$objRMSExcel->getActiveSheet()->SetCellValue('Z' . $i, "0.00");
				$objRMSExcel->getActiveSheet()->SetCellValue('AA' . $i, "0.00");
				$objRMSExcel->getActiveSheet()->SetCellValue('AB' . $i, "0.00");
				$objRMSExcel->getActiveSheet()->SetCellValue('AC' . $i, "0.00");
				$objRMSExcel->getActiveSheet()->SetCellValue('AD' . $i, "0.00");
				$objRMSExcel->getActiveSheet()->SetCellValue('AE' . $i, "0.00");
				$objRMSExcel->getActiveSheet()->SetCellValue('AF' . $i, "0.00");
				$objRMSExcel->getActiveSheet()->SetCellValue('AG' . $i, "0.00");
				$objRMSExcel->getActiveSheet()->SetCellValue('AH' . $i, "0.00");
				$objRMSExcel->getActiveSheet()->SetCellValue('AI' . $i, "0.00");
				$objRMSExcel->getActiveSheet()->SetCellValue('AJ' . $i, "0.00");
				$objRMSExcel->getActiveSheet()->SetCellValue('AK' . $i, "0.00");
				$objRMSExcel->getActiveSheet()->SetCellValue('AL' . $i, "0.00");
				$objRMSExcel->getActiveSheet()->SetCellValue('AM' . $i, "0.00");
				$objRMSExcel->getActiveSheet()->SetCellValue('AN' . $i, "0.00");
				$objRMSExcel->getActiveSheet()->SetCellValue('AO' . $i, "0.00");
				$objRMSExcel->getActiveSheet()->SetCellValue('AP' . $i, "0.00");
				$objRMSExcel->getActiveSheet()->getStyle('L' .$i.':AP'.$i)->applyFromArray($styleArray);
		    }
		}
   		/* ---------------------------------------------------------------------------------------------- */
		$expected_stocks = ($total_inv - $total);
        $pcount = $inventory->GetMonthlyPcount($cnt_start,$cnt_end,$days_cnt,$itemcode,$month,$year,$db);
        $variances = ($pcount - $expected_stocks);
        $variance_amount = ($function->GetUnitPriceRecords($itemcode,$year,$month,$db) * $variances);
        $shortages = ($variance_amount < 0) ? $variance_amount : 0;
        $overages = ($variance_amount > 0) ? $variance_amount : 0;

   		$objRMSExcel->getActiveSheet()->SetCellValue('AQ' . $i, number_format($total,2));
   		$objRMSExcel->getActiveSheet()->SetCellValue('AR' . $i, number_format($expected_stocks,2));
   		$objRMSExcel->getActiveSheet()->SetCellValue('AS' . $i, number_format($pcount,2));
   		$objRMSExcel->getActiveSheet()->SetCellValue('AT' . $i, number_format($variances,2));
   		$objRMSExcel->getActiveSheet()->SetCellValue('AU' . $i, $function->GetUnitPriceRecords($itemcode,$year,$month,$db));
   		$objRMSExcel->getActiveSheet()->SetCellValue('AV' . $i, number_format($variance_amount,2));
   		$objRMSExcel->getActiveSheet()->SetCellValue('AW' . $i, number_format($shortages,2));
   		$objRMSExcel->getActiveSheet()->SetCellValue('AX' . $i, number_format($overages,2));   	
   	    $objRMSExcel->getActiveSheet()->getStyle('AQ'. $i . ':AX'. $i)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_RIGHT);	
   	    $objRMSExcel->getActiveSheet()->getStyle('AQ' . $i . ':AX' . $i)->applyFromArray($styleArray);
		$variance_amount_total += $variance_amount;
	    $shortages_total += $shortages;
	    $overages_total += $overages;
	}
} else {
	
}
$bottom_total = ($i + 1);
$objRMSExcel->getActiveSheet()->SetCellValue('A'. $bottom_total, "");
$objRMSExcel->getActiveSheet()->SetCellValue('AQ'. $bottom_total, "TOTAL");
$objRMSExcel->getActiveSheet()->SetCellValue('AV'. $bottom_total, number_format($variance_amount_total));
$objRMSExcel->getActiveSheet()->SetCellValue('AW'. $bottom_total, number_format($shortages_total));
$objRMSExcel->getActiveSheet()->SetCellValue('AX'. $bottom_total, number_format($overages_total));
$objRMSExcel->getActiveSheet()->mergeCells('A' . $bottom_total . ':AP' . $bottom_total);
$objRMSExcel->getActiveSheet()->mergeCells('AQ' . $bottom_total . ':AU' . $bottom_total);

$objRMSExcel->getActiveSheet()->getStyle('A' . $bottom_total . ':AX' . $bottom_total)->getFont()->setBold(true);
$objRMSExcel->getActiveSheet()->getStyle('AR2:AX2')->applyFromArray($styleArray);
$objRMSExcel->getActiveSheet()->getStyle('A' . $bottom_total . ':AX' . $bottom_total)->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID)->getStartColor()->setRGB('F1F1F1');

$objRMSExcel->getActiveSheet()->getStyle('A' .$bottom_total.':AX'.$bottom_total)->applyFromArray($styleArray);
$objRMSExcel->getActiveSheet()->getStyle('AV' . $bottom_total . ':AX' . $bottom_total)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_RIGHT);
$objRMSExcel->getActiveSheet()->getStyle('A3:AX3')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
$objRMSExcel->getActiveSheet()->getStyle('AQ' . $bottom_total . ':AU' . $bottom_total)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
$debug = 0;
unset($styleArray);
if($debug == 0)
{
	$filename = $recipient.'_DBC_REPORT_'.$month_name.'_'.$year.'.xlsx';
	header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
	header('Content-Disposition: attachment; filename="' . $filename . '"');
	ob_start();	
	$objWriter = PHPExcel_IOFactory::createWriter($objRMSExcel, 'Excel2007');
	$objWriter->save('php://output');
	ob_end_flush();
}


