<?php
date_default_timezone_set('Asia/Manila');
include '../../../init.php';
$db = new mysqli(DB_HOST, DB_USER, DB_PASSWORD, DB_NAME);
require $_SERVER['DOCUMENT_ROOT']."/Plugins/PHPExcel/Classes/PHPExcel.php";
require $_SERVER['DOCUMENT_ROOT']."/Modules/DBC_Seasonal_Management/class/Class.inventory.php";
$inventory = new DBCInventory;
$year = $_REQUEST['year'];
$month = $_REQUEST['month'];
$date_string = $year."-".$month;
$_month = date("F", strtotime($date_string));
if($_REQUEST['limit'] != '' && $_REQUEST['category'] != '')
{
	$cat = $_REQUEST['category'];
	$limit = $_REQUEST['limit'];
	$q = "month='$month' AND year='$year' AND category='$cat' LIMIT $limit";
	$qq = "WHERE category='$cat' LIMIT $limit";
}
else if($_REQUEST['limit'] != '' && $_REQUEST['category'] == '')
{	
	$limit = $_REQUEST['limit'];
	$q = "month='$month' AND year='$year' LIMIT $limit";
	$qq = "LIMIT $limit";
}
else if($_REQUEST['limit'] == '' && $_REQUEST['category'] == '')
{	
	$limit = $_REQUEST['limit'];
	$q = "$month='$month' AND year='$year'";
	$qq =  "LIMIT $limit";
}

$min_leadtime = $inventory->GetLeadTime('average_leadtime',$db);
$max_leadtime = $inventory->GetLeadTime('max_leadtime',$db);
$days_count = 31;

$app_user = $_SESSION['dbc_seasonal_appnameuser'];
$date = date("F d, Y @ h:i A");
$title_date = date("Ymdhis");
$objRMSExcel = new PHPExcel();
$sqlList = $_REQUEST['columns'];
$tableName = $_REQUEST['table'];
$titleText = str_replace("dbc_seasonal_","", $tableName);
$titleText = strtoupper($titleText);
$titleText = str_replace("_", " ", $titleText);

$objRMSExcel->getActiveSheet()->SetCellValue('A1', $titleText." REPORT");
$objRMSExcel->getActiveSheet()->mergeCells('A1:I1');
$objRMSExcel->getActiveSheet()->getStyle('A1:I1')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
$objRMSExcel->getActiveSheet()->getStyle("A1")->getFont()->setBold(true);
$objRMSExcel->getActiveSheet()->getStyle('A1')->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID)->getStartColor()->setRGB('bddbe5');
$objRMSExcel->getActiveSheet()->getStyle("A1")->getFont()->setSize(18);
$objRMSExcel->getActiveSheet()->SetCellValue('A2', "Generated By - ". $app_user ." on ".$date);
$objRMSExcel->getActiveSheet()->mergeCells('A2:I2');
$objRMSExcel->getActiveSheet()->getStyle('A2:I2')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
$objRMSExcel->getActiveSheet()->getStyle("A1")->getFont()->setSize(14);

$objRMSExcel->getActiveSheet()->getStyle("A3:I3")->getFont()->setBold(true);
$objRMSExcel->getActiveSheet()->SetCellValue('A3', "SUPPLIER ID");
$objRMSExcel->getActiveSheet()->SetCellValue('B3', "ITEM CODE");
$objRMSExcel->getActiveSheet()->SetCellValue('C3', "ITEM DESCRIPTION");
$objRMSExcel->getActiveSheet()->SetCellValue('D3', "STOCK IN HAND");
$objRMSExcel->getActiveSheet()->SetCellValue('E3', "AVE. DAILY");
$objRMSExcel->getActiveSheet()->SetCellValue('F3', "MAX. DAILY");
$objRMSExcel->getActiveSheet()->SetCellValue('G3', "RE-ORDER LEVEL");
$objRMSExcel->getActiveSheet()->SetCellValue('H3', "SAFETY STOCKS");
$objRMSExcel->getActiveSheet()->SetCellValue('I3', "INVENTORY STATUS");

/* ###################################### DATA ######################################## */
$sqlQuery = "SELECT * FROM dbc_seasonal_inventory_stock $qq";
$results = mysqli_query($db, $sqlQuery);    
$i=4;
while($INVROW = mysqli_fetch_array($results))  
{
	$average=0;$safety_stocks=0;
	$rowid = $INVROW['inventory_id'];
	$supplier_id = $INVROW['supplier_id'];
	$item_code = $INVROW['item_code'];
	$item = $INVROW['item_description'];
	$stock_in_hand = $INVROW['stock_in_hand'];
				
	$sqlQueryRecords = "SELECT * FROM dbc_seasonal_inventory_records WHERE item_code='$item_code' AND $q";
	$invResults = mysqli_query($db, $sqlQueryRecords);    
    if ( $invResults->num_rows > 0 ) 
    {
    	while($INVENTORYROW = mysqli_fetch_array($invResults))  
		{
	    	$max_average=array();$cnt=array();$cnt=array();$max=0;
			for($i = 1; $i <= $days_count; $i++)
			{
				$x = str_pad($i, 2, '0', STR_PAD_LEFT);
				if($INVENTORYROW['day_'.$x] > 0)
				{
					$cnt++;
					$average += $INVENTORYROW['day_'.$x];
					$max = $INVENTORYROW['day_'.$x];
					$cnt[] = $INVENTORYROW['day_'.$x];
					$max_average[] = $max;
					$item_code = $INVENTORYROW['item_code'];							
				}												
			}
			$count=0;
			foreach ($cnt as $sales) {
			    $count = count($cnt);
			}
			if($count <= 0)
			{											
				$average_dr = 0;			
				$max_dr = 0;			
				$safety_stocks = 0;			
				$rol = 0;
			} else {
				$average_dr = round($average / $count);			
				$max_dr = max($max_average);			
				$safety_stocks = $max_dr * $max_leadtime - $average_dr * $min_leadtime;	
				$rol = $average_dr * $min_leadtime + $safety_stocks;
			}						
		}				
    } else {
	    $average_dr = 0;			
		$max_dr = 0;
    	$rol = 0;
    	$safety_stocks=0;
    }
    
    if($INVROW['stock_in_hand'] <= $safety_stocks)
	{
		$tdcell_text = "Re Order";
	} 
	elseif($INVROW['stock_in_hand'] < $rol)
	{
		$tdcell_text = "Re Order";
	} else {
		$tdcell_text = "Stock Sufficient";
	}   
    $objRMSExcel->getActiveSheet()->SetCellValue('A'.$i, $supplier_id);
	$objRMSExcel->getActiveSheet()->SetCellValue('B'.$i, $item_code);
	$objRMSExcel->getActiveSheet()->SetCellValue('C'.$i, $item);
	$objRMSExcel->getActiveSheet()->SetCellValue('D'.$i, $stock_in_hand);    
	$objRMSExcel->getActiveSheet()->SetCellValue('E'.$i, $average_dr);
	$objRMSExcel->getActiveSheet()->SetCellValue('F'.$i, $max_dr);
	$objRMSExcel->getActiveSheet()->SetCellValue('G'.$i, $rol);
	$objRMSExcel->getActiveSheet()->SetCellValue('H'.$i, $safety_stocks);
	$objRMSExcel->getActiveSheet()->SetCellValue('I'.$i, $tdcell_text);
	$i++;
}			
/* ################################################################################################ */
/* ##################################### EXCEL OUTPUT DATA ######################################## */
/* ################################################################################################ */
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment;filename="'.$titleText.'__REPORT_'.$title_date.'.xlsx"');
header('Cache-Control: max-age=0');
$objWriter = PHPExcel_IOFactory::createWriter($objRMSExcel, 'Excel2007');
ob_start();
$objWriter->save('php://output');
$fileData = ob_get_clean();
echo $fileData;
/* ################################################################################################ */
/* ############################### CREATED BY RONAN SARBON 2023 ################################### */
/* ################################################################################################ */
function generateExcelColumnNames($maxCount) {
    $columns = array();
    $letters = range('A', 'Z');

    $singleLetterCount = min(26, $maxCount);
    for ($i = 0; $i < $singleLetterCount; $i++) {
        $columns[] = $letters[$i];
    }
    $remainingCount = $maxCount - $singleLetterCount;
    if ($remainingCount > 0) {
        $doubleLetterCount = min(26, $remainingCount);
        for ($i = 0; $i < $doubleLetterCount; $i++) {
            foreach ($letters as $secondLetter) {
                $columns[] = $letters[$i] . $secondLetter;
                $remainingCount--;
                if ($remainingCount === 0) {
                    break 2; // Exit both loops when remainingCount reaches 0
                }
            }
        }
    }
    return $columns;
}